// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniCP.DbData;

#nullable disable

namespace UniCP.Migrations.MskDb
{
    [DbContext(typeof(MskDbContext))]
    [Migration("20260224071232_AddContractFilesTable")]
    partial class AddContractFilesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UniCP.Models.MsK.PARAMETRELER", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("Grup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametreAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_dbo.Parametrelers");

                    b.ToTable("PARAMETRELER");
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.Fn_Deneme", b =>
                {
                    b.Property<string>("ADI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDSI")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_SLA_ORAN", b =>
                {
                    b.Property<int>("AY")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ORAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UYAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UYMAYAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YIL")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_SLA_ORAN_COKLU", b =>
                {
                    b.Property<int>("AY")
                        .HasColumnType("int");

                    b.Property<string>("DONEM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<decimal>("ORAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UYAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UYMAYAN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YIL")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_TICKETLARI", b =>
                {
                    b.Property<string>("Bildirim_Aciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildirim_Bekletme_Neden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildirim_Durumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bildirim_No")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bildirim_Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bildirim_Tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gelis_Kanali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Musteri_Tipi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SLA_YD_Cozum_Kalan_Sure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SLA_YD_Cozum_Sure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sla")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sonislemtarih")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_TICKETLARI_COKLU", b =>
                {
                    b.Property<string>("Bildirim_Aciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildirim_Bekletme_Neden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildirim_Durumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bildirim_No")
                        .HasColumnType("int");

                    b.Property<DateTime>("Bildirim_Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bildirim_Tipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gelis_Kanali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<string>("Musteri_Tipi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SLA_YD_Cozum_Kalan_Sure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SLA_YD_Cozum_Sure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sla")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sonislemtarih")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_TICKET_DURUM_SAYILARI", b =>
                {
                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sayi")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_N4B_TICKET_DURUM_SAYILARI_COKLU", b =>
                {
                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<int>("Sayi")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_TFS_GELISTIRME", b =>
                {
                    b.Property<string>("ACANKULLANICI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ACILMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("COST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DEGISTIRMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GERCEKLESEN_CANLITESLIM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GERCEKLESEN_PYUAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("MADDEBASLIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADDEDURUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUSTERI_SORUMLUSU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PLANLANAN_PYUAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PLANLAN_CANLITESLIM")
                        .HasColumnType("datetime2");

                    b.Property<string>("PROJE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SATISDURUMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SATIS_SORUMLUSU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TAMAMLANMA_OARANI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TFSNO")
                        .HasColumnType("int");

                    b.Property<string>("URUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YARATICI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YAZILIM_TOPLAMAG")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_TFS_GELISTIRME_COKLU", b =>
                {
                    b.Property<string>("ACANKULLANICI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ACILMATARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("COST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DEGISTIRMETARIHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GERCEKLESEN_CANLITESLIM")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GERCEKLESEN_PYUAT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<string>("MADDEBASLIK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MADDEDURUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MUSTERI_SORUMLUSU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PLANLANAN_PYUAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PLANLAN_CANLITESLIM")
                        .HasColumnType("datetime2");

                    b.Property<string>("PROJE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SATISDURUMU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SATIS_SORUMLUSU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TAMAMLANMA_OARANI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TFSNO")
                        .HasColumnType("int");

                    b.Property<string>("URUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YARATICI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("YAZILIM_TOPLAMAG")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_VARUNA_CHART_DATA", b =>
                {
                    b.Property<string>("GRUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("STOKKOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TOPLAMTUTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("URUNADI")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_VARUNA_CHART_DATA_COKLU", b =>
                {
                    b.Property<string>("GRUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("KDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LNGKOD")
                        .HasColumnType("int");

                    b.Property<string>("STOKKOD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TARIH")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TOPLAMTUTAR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("URUNADI")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_VARUNA_SIPARIS_COKLU", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bekleme_Gun")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bekleyen_Bakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmOrderNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrmSalesOfficeSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionChannelSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fatura_toplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Gecikme_Gun")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEligibleForNetsisIntegration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligibleForSapIntegration")
                        .HasColumnType("bit");

                    b.Property<int>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTypeTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalOwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPOutReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesDocumentTypeSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroupSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrganizationSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Satıs_Vadesi")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tahsil_Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalAmountWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalProfitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_VARUNA_SIPARIS_DETAY", b =>
                {
                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LNGKOD")
                        .HasColumnType("int");

                    b.Property<decimal?>("LineDiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetLineTotalWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PRODUCTSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYPSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SSP_VARUNA_SIPARIS_DETAY_COKLU", b =>
                {
                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LNGORTAKPROJEKOD")
                        .HasColumnType("int");

                    b.Property<decimal?>("LineDiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NetLineTotalWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRODUCTSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PYPSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockUnitType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.SpVarunaSiparisResult", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Bekleme_Gun")
                        .HasColumnType("int");

                    b.Property<decimal?>("Bekleyen_Bakiye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrmOrderNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrmSalesOfficeSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistributionChannelSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fatura_toplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Gecikme_Gun")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEligibleForNetsisIntegration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligibleForSapIntegration")
                        .HasColumnType("bit");

                    b.Property<int>("LNGKOD")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTypeTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposalOwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SAPOutReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesDocumentTypeSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesGroupSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrganizationSapId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Satıs_Vadesi")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTotalDiscount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tahsil_Tarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalAmountWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalNetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalProfitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.SpModels.Sp_Deneme", b =>
                {
                    b.Property<int>("P1")
                        .HasColumnType("int");

                    b.Property<string>("P2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ST")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_FINANS_ONAY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PONumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RevokedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RevokedBy");

                    b.HasIndex(new[] { "OrderId" }, "IX_TBL_FINANS_ONAY_OrderId");

                    b.ToTable("TBL_FINANS_ONAY");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_KULLANICI", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int?>("LNGIDENTITYKOD")
                        .HasColumnType("int");

                    b.Property<int?>("LNGKULLANICITIPI")
                        .HasColumnType("int");

                    b.Property<int?>("LNGORTAKFIRMAKOD")
                        .HasColumnType("int");

                    b.Property<string>("TXTADSOYAD")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TXTEMAIL")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("TXTFIRMAADI")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.HasKey("LNGKOD");

                    b.ToTable("TBL_KULLANICI");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_KULLANICI_FIRMA", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int>("LNGFIRMAKOD")
                        .HasColumnType("int");

                    b.Property<int>("LNGKULLANICIKOD")
                        .HasColumnType("int");

                    b.HasKey("LNGKOD");

                    b.HasIndex(new[] { "LNGFIRMAKOD" }, "IX_TBL_KULLANICI_FIRMA_FirmaKod");

                    b.HasIndex(new[] { "LNGKULLANICIKOD" }, "IX_TBL_KULLANICI_FIRMA_KullaniciKod");

                    b.ToTable("TBL_KULLANICI_FIRMA");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_N4BISSSEFILE", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<string>("FileBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LNGTBLISSUEKOD")
                        .HasColumnType("int");

                    b.HasKey("LNGKOD");

                    b.HasIndex("LNGTBLISSUEKOD");

                    b.ToTable("TBL_N4BISSSEFILES");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_N4BISSUE", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Durum")
                        .HasColumnType("int");

                    b.Property<int?>("IssueId")
                        .HasColumnType("int");

                    b.Property<int?>("IssueTypeID")
                        .HasColumnType("int");

                    b.Property<string>("TXTBILDIRIMACIKALAMA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXTBILDIRIMBASLIK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LNGKOD");

                    b.ToTable("TBL_N4BISSUES");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_SISTEM_LOG", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int?>("LNGKULLANICIKOD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRHKAYIT")
                        .HasColumnType("datetime2");

                    b.Property<string>("TXTDETAY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXTIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TXTISLEM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TXTKULLANICIADI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TXTMODUL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LNGKOD");

                    b.ToTable("TBL_SISTEM_LOGs");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<string>("BYTDURUM")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<decimal?>("DEC_EFOR")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("INT_ANKET_PUAN")
                        .HasColumnType("int");

                    b.Property<int?>("LNGPROJEKOD")
                        .HasColumnType("int");

                    b.Property<int?>("LNGTFSNO")
                        .HasColumnType("int");

                    b.Property<int?>("LNGVARUNAKOD")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRHKAYIT")
                        .HasColumnType("datetime");

                    b.Property<string>("TXTTALEPACIKLAMA")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("TXTTALEPBASLIK")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("TXT_ANKET_NOT")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TXT_PO")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TXT_SORUMLULAR")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("LNGKOD");

                    b.HasIndex(new[] { "TRHKAYIT" }, "IX_TBL_TALEP_TrhKayit");

                    b.ToTable("TBL_TALEP");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_AKISDURUMLARI", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<string>("TXTDURUMADI")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("LNGKOD");

                    b.ToTable("TBL_TALEP_AKISDURUMLARI");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_AKIS_LOG", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int?>("LNGBASLANGICKULLANICI")
                        .HasColumnType("int");

                    b.Property<int?>("LNGDURUMKOD")
                        .HasColumnType("int");

                    b.Property<int?>("LNGGERIALKULLANICI")
                        .HasColumnType("int");

                    b.Property<int?>("LNGONAYKULLANICI")
                        .HasColumnType("int");

                    b.Property<int?>("LNGSIRA")
                        .HasColumnType("int");

                    b.Property<int?>("LNGTALEPKOD")
                        .HasColumnType("int");

                    b.Property<int?>("LNGTFSNO")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TRHDURUMBASLANGIC")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TRHDURUMGERIALMA")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("TRHDURUMONAY")
                        .HasColumnType("datetime");

                    b.HasKey("LNGKOD");

                    b.HasIndex("LNGDURUMKOD");

                    b.ToTable("TBL_TALEP_AKIS_LOG");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_FILE", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<string>("FileBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LNGTALEPKOD")
                        .HasColumnType("int");

                    b.HasKey("LNGKOD");

                    b.HasIndex("LNGTALEPKOD");

                    b.ToTable("TBL_TALEP_FILES");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_NOTLAR", b =>
                {
                    b.Property<int>("LNGKOD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LNGKOD"));

                    b.Property<int?>("BYTDURUM")
                        .HasColumnType("int");

                    b.Property<int?>("LNGKULLANICIKOD")
                        .HasColumnType("int");

                    b.Property<int?>("LNGTALEPKOD")
                        .HasColumnType("int");

                    b.Property<string>("TXTNOT")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("LNGKOD");

                    b.HasIndex("LNGTALEPKOD");

                    b.ToTable("TBL_TALEP_NOTLAR");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_SOZLESME", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("TBL_VARUNA_SOZLESME");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_SOZLESME_DOSYALAR", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ContractId");

                    b.ToTable("TBL_VARUNA_SOZLESME_DOSYALAR");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_SOZLESME_INVENTORYITEM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InventoryItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TBL_VARUNA_SOZLESME_INVENTORYITEM");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_TEKLIF_URUNLERI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetLineSubTotalLocal_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetLineTotalAmount_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TBL_VARUNA_TEKLIF_URUNLERI");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TblZabbixHostList", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HOSTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostId"));

                    b.Property<int?>("LngOrtakProjeKod")
                        .HasColumnType("int")
                        .HasColumnName("LNGORTAKPROJEKOD");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("HostId");

                    b.ToTable("TBL_ZABBIX_HOST_LIST");
                });

            modelBuilder.Entity("UniCP.Models.MsK.VIEW_N4BISSUE", b =>
                {
                    b.Property<string>("Bildirim_Aciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildirim_Bekletme_Neden")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Bildirim_Durumu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bildirim_Giren")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bildirim_Giren_Kullanici_Adi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Bildirim_No")
                        .HasColumnType("int");

                    b.Property<string>("Bildirim_Sahibi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bildirim_Sahibi_Kullanici_Adi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Bildirim_Tarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Bildirim_Tipi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bildirim_Url")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Bildirim_Ustlenen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Bildirim_Ustlenen_Kullanici_Adi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cevap_Verilen_Kanallar1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cozum_Aciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gelis_Kanali")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kategori_Adi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Kategori_No")
                        .HasColumnType("int");

                    b.Property<string>("Kategori_Yolu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kullanici_Bolum")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Musteri_Adi")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Musteri_Notu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Olusturulma_Tarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Oncelik")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("SLA_Ilk_Mudahale_Kalan_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_Ilk_Mudahale_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_Ilk_Mudahale_Top_Gecen_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<string>("SLA_Ilk_Mudahale_Uyum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SLA_Kalan_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_Toplam_Gecen_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<string>("SLA_Uyum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SLA_YD_Cozum_Kalan_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_YD_Cozum_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<decimal?>("SLA_YD_Cozum_Toplam_Gecen_Sure")
                        .HasColumnType("decimal(28, 2)");

                    b.Property<string>("SLA_YD_Cozum_Uyum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Sonislemtarih")
                        .HasColumnType("datetime");

                    b.Property<string>("Support_L1_L2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tercih_Edilen_Geri_Dönüs_Metodu2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable((string)null);

                    b.ToView("VIEW_N4BISSUES", (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.VIEW_N4BISSUESLIFECYCLE", b =>
                {
                    b.Property<DateTime?>("ActionEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ActionStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Bidirim_BEkletme_Neden")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("EndDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EscalationTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GroupID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Islendi")
                        .HasColumnType("tinyint");

                    b.Property<int?>("IssueLifeCycleID")
                        .HasColumnType("int");

                    b.Property<int?>("IssueLifeIssueId")
                        .HasColumnType("int");

                    b.Property<string>("IssuerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionStatusID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResolutionStatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Sonislemtarih")
                        .HasColumnType("datetime");

                    b.Property<string>("StartDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Tarihce_Sira")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserGroupID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserGroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable((string)null);

                    b.ToView("VIEW_N4BISSUESLIFECYCLE", (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.VIEW_N4B_KATEGORILER", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentCategoryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Sonislemtarih")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("UnDeleted")
                        .HasColumnType("tinyint");

                    b.HasKey("CategoryID");

                    b.ToTable("VIEW_N4B_KATEGORILER");

                    b.ToView("VIEW_N4B_KATEGORILER", (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.VIEW_ORTAK_PROJE_ISIMLERI", b =>
                {
                    b.Property<int>("LNGKOD")
                        .HasColumnType("int");

                    b.Property<string>("TXTORTAKPROJEADI")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.ToTable("VIEW_ORTAK_PROJE_ISIMLERI");

                    b.ToView("VIEW_ORTAK_PROJE_ISIMLERI", (string)null);
                });

            modelBuilder.Entity("UniCP.Models.MsK.WWDENEME", b =>
                {
                    b.Property<int>("BIR")
                        .HasColumnType("int");

                    b.Property<int>("IKI")
                        .HasColumnType("int");

                    b.Property<string>("ST")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.ToTable((string)null);

                    b.ToView("WWDENEME", (string)null);
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("UniCP.Models.MsK.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniCP.Models.MsK.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetRoleClaim", b =>
                {
                    b.HasOne("UniCP.Models.MsK.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserClaim", b =>
                {
                    b.HasOne("UniCP.Models.MsK.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserLogin", b =>
                {
                    b.HasOne("UniCP.Models.MsK.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUserToken", b =>
                {
                    b.HasOne("UniCP.Models.MsK.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_FINANS_ONAY", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_KULLANICI", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("UniCP.Models.MsK.TBL_KULLANICI", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("RevokedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_N4BISSSEFILE", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_N4BISSUE", "LNGTBLISSUEKODNavigation")
                        .WithMany("TBL_N4BISSSEFILEs")
                        .HasForeignKey("LNGTBLISSUEKOD")
                        .HasConstraintName("FK_TBL_N4BISSSEFILES_TBL_N4BISSUES");

                    b.Navigation("LNGTBLISSUEKODNavigation");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_AKIS_LOG", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_TALEP_AKISDURUMLARI", "LNGDURUMKODNavigation")
                        .WithMany("TBL_TALEP_AKIS_LOGs")
                        .HasForeignKey("LNGDURUMKOD")
                        .HasConstraintName("FK_TBL_TALEP_AKIS_LOG_TBL_TALEP_AKISDURUMLARI");

                    b.Navigation("LNGDURUMKODNavigation");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_FILE", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_TALEP", "LNGTALEPKODNavigation")
                        .WithMany("TBL_TALEP_FILEs")
                        .HasForeignKey("LNGTALEPKOD")
                        .HasConstraintName("FK_TBL_TALEP_FILES_TBL_TALEP");

                    b.Navigation("LNGTALEPKODNavigation");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_NOTLAR", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_TALEP", "LNGTALEPKODNavigation")
                        .WithMany("TBL_TALEP_NOTLARs")
                        .HasForeignKey("LNGTALEPKOD")
                        .HasConstraintName("FK_TBL_TALEP_NOTLAR_TBL_TALEP");

                    b.Navigation("LNGTALEPKODNavigation");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_SOZLESME_DOSYALAR", b =>
                {
                    b.HasOne("UniCP.Models.MsK.TBL_VARUNA_SOZLESME", "Contract")
                        .WithMany("Dosyalar")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("UniCP.Models.MsK.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_N4BISSUE", b =>
                {
                    b.Navigation("TBL_N4BISSSEFILEs");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP", b =>
                {
                    b.Navigation("TBL_TALEP_FILEs");

                    b.Navigation("TBL_TALEP_NOTLARs");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_TALEP_AKISDURUMLARI", b =>
                {
                    b.Navigation("TBL_TALEP_AKIS_LOGs");
                });

            modelBuilder.Entity("UniCP.Models.MsK.TBL_VARUNA_SOZLESME", b =>
                {
                    b.Navigation("Dosyalar");
                });
#pragma warning restore 612, 618
        }
    }
}
